# ----------------------- #
#      Main Configs       #
# ----------------------- #

url: http://www.brightn.se
title: Brightn
email: simon@brightn.se
author: Simon Nordberg
description: > # "Write an awesome description for your new site here.
copyright: 'Copyright &copy; 2016 Brightn AB. All Rights Reserved.'
credits: ''

# ----------------------- #
#    Jekyll & Plugins     #
# ----------------------- #

# Build settings
markdown: kramdown
permalink: pretty

# ----------------------- #
#   3rd Party Settings    #
# ----------------------- #

social:
  - title: linkedin
    url: https://www.linkedin.com/company/brightn
  - title: github
    url: https://github.com/brightnse
